### ISSUE TITLE
v2: WebGL context errors while loading on mobile

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#478]
Getting stack traced when I try to run RapiD on mobile now: 

```
AtlasResource.ts:150 Uncaught TypeError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'.
    at AtlasResource.uploadItem (AtlasResource.ts:150:1)
    at AtlasResource.upload (AtlasResource.ts:112:1)
    at TextureSystem2.updateTexture (TextureSystem.ts:329:50)
    at TextureSystem2.bind (TextureSystem.ts:168:22)
    at BatchPlugin.AbstractBatchRenderer2.bindAndClearTexArray (AbstractBatchRenderer.ts:464:27)
    at BatchPlugin.AbstractBatchRenderer2.drawBatches (AbstractBatchRenderer.ts:520:22)
    at BatchPlugin.AbstractBatchRenderer2.flush (AbstractBatchRenderer.ts:545:14)
    at Renderer3.render (Renderer.ts:519:36)
    at Application3.render (Application.ts:131:23)
    at TickerListener2.emit (TickerListener.ts:68:25)
uploadItem @ AtlasResource.ts:150
upload @ AtlasResource.ts:112
TextureSystem2.updateTexture @ TextureSystem.ts:329
TextureSystem2.bind @ TextureSystem.ts:168
AbstractBatchRenderer2.bindAndClearTexArray @ AbstractBatchRenderer.ts:464
AbstractBatchRenderer2.drawBatches @ AbstractBatchRenderer.ts:520
AbstractBatchRenderer2.flush @ AbstractBatchRenderer.ts:545
Renderer3.render @ Renderer.ts:519
Application3.render @ Application.ts:131
TickerListener2.emit @ TickerListener.ts:68
Ticker2.update @ Ticker.ts:444
(anonymous) @ PixiRenderer.js:148
requestAnimationFrame (async)
render @ PixiRenderer.js:146
redraw @ map.js:477
invokeFunc @ debounce.js:95
leadingEdge @ debounce.js:105
debounced @ debounce.js:172
map.deferredRedraw @ map.js:258
image.onload @ PixiLayerBackgroundTiles.js:208
load (async)
(anonymous) @ PixiLayerBackgroundTiles.js:193
renderTileSource @ PixiLayerBackgroundTiles.js:174
(anonymous) @ PixiLayerBackgroundTiles.js:78
render @ PixiLayerBackgroundTiles.js:65
(anonymous) @ PixiLayers.js:70
render @ PixiLayers.js:70
render @ PixiRenderer.js:141
redraw @ map.js:477
map.immediateRedraw @ map.js:266
call @ dispatch.js:57
background.baseLayerSource @ background.js:355
(anonymous) @ background.js:497
Promise.then (async)
background.ensureLoaded @ background.js:482
initializeDependents @ context.js:563
context.init @ context.js:517
checkScript @ (index):60
load (async)
(anonymous) @ (index):33
```

**Comment by Bonkles** [comment]
Update: compared the call stacks of mobile vs. desktop runs, and it looks like the fifth parameter of type `AtlasResourceItem` being passed to `this.uploadItem()` in AtlasResource.ts has a different 'source' type on desktop vs. mobile. 

On mobile, the source is an 'img': 

![image](https://user-images.githubusercontent.com/1887955/170308997-c5e367b6-04b7-40f8-84e6-5cab392af0e0.png)


Whereas on desktop the source is a UInt8Array: 

![image](https://user-images.githubusercontent.com/1887955/170309462-571e8a3c-4b6e-4cbc-bdd0-cc9319d9ac70.png)

**Comment by bhousel** [comment]
Interesting - yeah I'll check it out! 
The relevant texture atlas code is in here:
https://github.com/ShukantPal/pixi-essentials/blob/master/packages/texture-allocator/src/AtlasResource.ts

My intent was to pass the `HTMLImageElement` directly to the allocator.. Maybe I need to work with pixel data instead in some environments 🤔 

https://github.com/facebookincubator/RapiD/blob/dc5d009c1d0b0179305bdf08d424191c31ab38e6/modules/pixi/PixiLayerBackgroundTiles.js#L193-L199

**Comment by bhousel** [comment]
Update: @Bonkles figured out the root cause - we should make sure our code works with WebGL1, since [mobile browsers as recent as last year](https://caniuse.com/webgl2) are still using it.

In other words, [texSubImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texSubImage2D) should be called with an `ArrayBufferView`

**Comment by bhousel** [comment]
This was done in f5e473795 , 4649b1d58
