### ISSUE TITLE
WebGLRenderingContext error on mobile devices / WebGL v1

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#493]
When starting safari desktop in webGL v1 mode, or when using chrome on mobile, I receive the following error: 

```
PixiLayerOsm.js:150 Uncaught TypeError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'.
    at AtlasResource.uploadItem (PixiLayerOsm.js:150:1)
    at AtlasResource.upload (PixiLayerOsm.js:112:1)
    at TextureSystem2.updateTexture (BufferSystem.ts:314:50)
    at TextureSystem2.bind (BufferSystem.ts:161:22)
    at AbstractBatchRenderer2.bindAndClearTexArray (BatchPluginFactory.ts:456:27)
    at AbstractBatchRenderer2.drawBatches (BatchPluginFactory.ts:512:22)
    at AbstractBatchRenderer2.flush (BatchPluginFactory.ts:537:14)
    at AbstractBatchRenderer2.stop (BatchPluginFactory.ts:564:14)
    at BatchSystem2.setObjectRenderer (FramebufferSystem.ts:42:30)
    at BatchSystem2.flush (FramebufferSystem.ts:54:14)
```

**Comment by Bonkles** [comment]
Confirmed that there is a short-term bug with source maps in Chrome 103 (the current version) and have also confirmed that the bug has been found and fixed in chrome 104/105.

**Comment by Bonkles** [comment]
Closing this one- we made the switch to webGL v2 preference for all platforms, seems to be working well.

**Comment by ShukantPal** [comment]
Wow, I didn't know Facebook was using my library :heart:.
