### ISSUE TITLE
Draw new point/line/area is not working.

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#499]
When I click on the 'Add Feature' buttons (point/line/area) in the top toolbar, I am getting console errors. 

Clicking the 'Add point' button for the first time results in this message:  

 ```
 Uncaught TypeError: context2._currMode.enter is not a function
    at context2.enter (iD.js:109396:43)
    at HTMLButtonElement.<anonymous> (iD.js:106089:24)
    at HTMLButtonElement.<anonymous> (date.js:3:14)
```

If I then click the 'Add Line' button, I get: 

```
Uncaught TypeError TypeError: currMode.exit is not a function
    at context2.enter (/Users/clarkben/working/RapiD/modules/core/context.js:355:16)
    at <anonymous> (/Users/clarkben/working/RapiD/modules/ui/tools/modes.js:103:23)
    at <anonymous> (/Users/clarkben/working/RapiD/node_modules/d3-selection/src/selection/on.js:3:14)
```

**Comment by Bonkles** [comment]
After discussing with Bryan, it seems that these behaviors aren't quite fully baked. will check this later after they're done!

**Comment by Bonkles** [comment]
Update: It looks like drawing new points and lines does work. Drawing areas still doesn't quite engage the correct behavior.

**Comment by Bonkles** [comment]
Bug is stale- we now have all three drawing modes code-complete.
