### ISSUE TITLE
Shift-R is not working for enabling/disabling the rapid layer.

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#515]
Hitting Shift-R generates: 

`Uncaught TypeError TypeError: layer.visible is not a function
    at toggleFeatures (/Users/clarkben/working/RapiD/modules/ui/tools/rapid_features.js:33:11)
    at <anonymous> (/Users/clarkben/working/RapiD/modules/ui/tools/rapid_features.js:54:9)
    at testBindings (/Users/clarkben/working/RapiD/modules/util/keybinding.js:25:25)
    at bubble (/Users/clarkben/working/RapiD/modules/util/keybinding.js:104:9)
    at <anonymous> (/Users/clarkben/working/RapiD/node_modules/d3-selection/src/selection/on.js:3:14)
`

**Comment by Bonkles** [comment]
Turns out there was some old code controlling this key logic that was written before the refactor into scenes/layers. 

Updated the calls to use the scene's `getLayer` call to get the rapid layer, toggle its 'enabled' flag, and then call a map redraw.
