### ISSUE TITLE
Error when selecting photo imagery

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#548]
When clicking on a mapillary photo, I see the following error: 

```
/Users/clarkben/working/RapiD/node_modules/@pixi/utils/src/browser/hello.ts:45
Uncaught TypeError TypeError: renderer.selectFeatures is not a function
    at _processClick (/Users/clarkben/working/RapiD/modules/behaviors/BehaviorSelect.js:460:16)
    at _pointerup (/Users/clarkben/working/RapiD/modules/behaviors/BehaviorSelect.js:245:12)
    at emit (/Users/clarkben/working/RapiD/node_modules/eventemitter3/index.js:202:33)
    at InteractionManager2.onPointerComplete (/Users/clarkben/working/RapiD/node_modules/@pixi/interaction/src/InteractionManager.ts:1242:18)
    at InteractionManager2.onPointerUp (/Users/clarkben/working/RapiD/node_modules/@pixi/interaction/src/InteractionManager.ts:1302:14)
_processClick @ /Users/clarkben/working/RapiD/modules/behaviors/BehaviorSelect.js:460:16
```

**Comment by Bonkles** [comment]
Fixed in 9e2599797 and fdd725ec4.
